### ISSUE TITLE
Aligned RGB and thermal pairs

### ISSUE THREAD

**Issue by Neal2020GitHub** [yvette256/nerfstudio-thermal#5]
Hi, authors! 

It seems that the RGB and thermal images are not aligned after running `ns-process-data`. I am wondering how I could obtain the aligned RGB and thermal pairs so that I could do some experiments on this dataset. 

Many thanks!

**Comment by yvette256** [comment]
Hi, thanks for the interest in our work! I am not sure if this addresses your question, but please note it is expected for the RGB and thermal images after being extracted from the FLIR images to appear visually slightly non-aligned (e.g. not from exactly the same perspective) due to the different camera parameters of the RGB and thermal cameras. This should not be an issue in practice due to the calibration process which computes the camera parameters of the RGB and thermal cameras, accounting for this discrepancy. Please let me know if I've misunderstood your issue and can answer your question differently!

**Comment by Neal2020GitHub** [comment]
It answers my question. Thank you!
